name: CI - cv-nginx

on:
  push:
    branches: ['main']
env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: my-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::776410619441:role/github-actions-cicd
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64 ,linux/amd64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest #, $--{{ steps.login-ecr.outputs.registry }}/$--{{ env.ECR_REPOSITORY }}:$--{{ steps.increment-git-tag.outputs.git-tag }} # or use :$(date +%s)